### PR TITLE
Refactor reporter & fix filter and copy snippet bugs

### LINKED ISSUE #8: "Bom saved at" with empty path
even i dont specify any path for storing bom, then also we are printing this line

Image

### PR DESCRIPTION
**Pull request by OmkarPh**

### CODE REVIEW

File: pkg/codeanalysis/codeanalysis.go [hunk 1]
```diff
@@ -10,40 +10,58 @@ import (
...
 	if err != nil {
 		w.config.Callbacks.OnErr("failed to perform codeanalysis", err)
-		return fmt.Errorf("failed to perform codeanalysis: %w", err)
+		return nil, fmt.Errorf("failed to perform codeanalysis: %w", err)
+	}
+
+	err = w.reportCodeAnalysisFindings()
+	if err != nil {
+		w.config.Callbacks.OnErr("failed to report code analysis findings", err)
+		return nil, fmt.Errorf("failed to report code analysis findings: %w", err)
```
Comment (abhisek) [inline pkg/codeanalysis/codeanalysis.go:49]: Can we avoid duplicate strings here? We can probably define the error strings as constant and then use `errors.Wrap(...)` to wrap an error with context (string)

File: pkg/reporter/html.go [hunk 2]
```diff
@@ -174,8 +109,111 @@ func VisualiseCodeAnalysisFindings(codeAnalysisFindings *codeanalysis.CodeAnalys
...
+		headers: headers,
+		rows:    []map[string]interface{}{},
+	}
+}
+
+func (hv *HTMLVisualiser) AddRow(row map[string]interface{}) {
+	hv.rows = append(hv.rows, row)
+}
+
+func (hv *HTMLVisualiser) GenerateHtmlFile(htmlPath string) error {
```
Comment (abhisek) [inline pkg/reporter/html.go:161]: We should have some basic unit tests to ensure structural correctness of the generated HTML report.

File: pkg/reporter/templates/report.html [hunk 3]
```diff
@@ -1,147 +1,310 @@
...
+        function filterTable() {
+          const selectedSignatures = signatureChoices
+            .getValue()
+            .map((item) => item.value);
+          const selectedTags = tagsChoices.getValue().map((item) => item.value);
+          const rows = document.querySelectorAll("#signatureTable > tr");
+
+          for (let i = 0; i < rows.length; i += 2) {
+            const row = rows[i];
+            const detailsRow = rows[i + 1];
```
[the remark this answers is not in the document]
Comment (OmkarPh) [reply pkg/reporter/templates/report.html]: ack

**Review by abhisek — APPROVED** [review]
